### ISSUE TITLE
9.1.1 cannot import lib/index.js

### ISSUE THREAD

**Issue by Adam-Collier** [rehypejs/rehype-remark#12]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.1.1

### Steps to reproduce

You can see what it is erroring out here: https://cdn.skypack.dev/rehype-remark@9.1.1 and the error message from skypack here: https://cdn.skypack.dev/error/build:rehype-remark@v9.1.1-b794CTg7VAHMel9jwx8s 

This is also happening when trying to use the package locally

### Expected behavior

We should be able to import the library without any issues

### Actual behavior

The lib directory doesn't look to be built so when we try and import the package it's looking for a file that doesn't exist and errors.

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

**Comment by wooorm** [comment]
Thanks!
