### ISSUE TITLE
Incorrect bold parsing in CJK on Markdown

### ISSUE THREAD

**Issue by shtse8** [rehypejs/rehype-remark#13]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

Convert following html to remark
```html
<strong>
Hello Gamer
</strong>
```

it will be failed to be strong in markdown.

### Expected behavior

**Hello Gamer**

### Actual behavior

**Hello Gamer **

### Runtime

Node v16

### Package manager

yarn 1

### OS

Windows

**Comment by wooorm** [comment]
Please expand on the steps to reproduce in more detail, such as by providing code.

**Comment by shtse8** [comment]
**這場大型粉絲見面活動有什麼亮點？**我們邀請到 FTX

**Comment by shtse8** [comment]
Sorry, my fault. Many plugins I'm using. I don't know which exactly causing the issue.
I am posting code here to reproduce the case.

```js
const text = '<strong>「台灣」</strong>主題'
const markdown = String(await unified()
  .use(rehypeParse, { fragment: true })
  .use(rehypeRemark)
  .use(() => tree => console.log(inspect(tree)))
  .use(remarkStringify)
  .process(text))
console.log(markdown)
```

Result:
```
root[1] (1:1-1:24, 0-23)
└─0 paragraph[2]
    ├─0 strong[1] (1:1-1:22, 0-21)
    │   └─0 text "「台灣」" (1:9-1:13, 8-12)
    └─1 text "主題" (1:22-1:24, 21-23)
**「台灣」**主題
```
Perfect parsing result.
with markdown `**「台灣」**主題`


Ok, now we convert it back.

```js
const text = '**「台灣」**主題'
const html = String(await unified()
  .use(remarkParse)
  .use(() => tree => console.log(inspect(tree)))
  .use(remarkRehype)
  .use(rehypeStringify)
  .process(text))
console.log(html)
```

Result
```html
<p>**「台灣」**主題</p>
```

the strong is broken.

**Comment by ChristianMurphy** [comment]
This looks related to https://talk.commonmark.org/t/bold-failure-in-chinese-sentence-because-of-the-usage-of-chinese-punctuation-is-different-from-english/3478
and is likely also related to https://github.com/syntax-tree/unist/discussions/60

**Comment by shtse8** [comment]
> This looks related to https://talk.commonmark.org/t/bold-failure-in-chinese-sentence-because-of-the-usage-of-chinese-punctuation-is-different-from-english/3478 and is likely also related to [syntax-tree/unist#60](https://github.com/orgs/syntax-tree/discussions/60)

Yes, exactly related to the first link you provided.
Due to this issue, I can't convert my Chinese articles forward and backward.

**Comment by wooorm** [comment]
This problem has two parts:

a) markdown does not support this CJS + whitespace attention (emphasis, strong). If you want markdown to support this, you’re out of luck. We follow commonmark, commonmark doesn’t support that, so it won’t land.

b) if you care about roundtripping from HTML *with* whitespace, to markdown *without* whitespace, which you feel is broken, the problem *would* be in `mdast-util-to-mdast`, however (https://github.com/syntax-tree/mdast-util-to-markdown/issues/54), and is similar to https://github.com/orgs/syntax-tree/discussions/60#discussioncomment-2111096. This could solve your problem but will generate unpretty markup (it’ll inject character references)

**Comment by wooorm** [comment]
If you think approach b) is a good one, please open an issue on `mdast-util-to-mdast`. Thanks!

**Comment by shtse8** [comment]
> If you think approach b) is a good one, please open an issue on `mdast-util-to-mdast`. Thanks!

it's because the bug of `commonmark`. nothing wrong with rehype.
I am sad that `strong` is not fully applicate to Chinese.
I added a directive to handle strong in this case.
Hope commonmark will solve this issue soon.

**Comment by wooorm** [comment]
> Hope commonmark will solve this issue soon.

This is unfortunately unlikely. Emphasis and strong are really hard to get right. These rules are definitely not perfect, as this case shows, but a) what rules would be perfect? b) changing the rules would break a lot of existing markdown.

You might be interested in https://github.com/jgm/djot, which solves this issue
