### ISSUE TITLE
Problem when HTML contains `&`

### ISSUE THREAD

**Issue by alessandroliveri** [rehypejs/rehype-remark#14]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-remark 9.1.2, remark-stringify 10.0.2, rehype-parse 8.0.4

### Steps to reproduce

```import { unified } from 'unified';
import rehypeParse from 'rehype-parse';
import rehypeRemark from 'rehype-remark';
import remarkStringify from 'remark-stringify';

main();

async function main() {
  const file = unified()
      .use(rehypeParse)
      .use(rehypeRemark)
      .use(remarkStringify)
      .processSync('<h1>Q&A</h1>');

  console.log(String(file));
}
```

### Expected behavior

The output should be ```# Q&A ```

### Actual behavior

The output is ```# Q\&A```
Looking at the generated string it looks like `#Q\\&A` instead of `#Q\&A`

### Runtime

Node v16

### Package manager

npm 8

### OS

macOS

**Comment by wooorm** [comment]
This is expected behavior. Certain punctuation marks, in certain circumstances, can turn into markdown constructs. Such as an asterisk into emphasis. The rules are complex. In this case, `&`, followed by `#` or a letter, can turn into a character reference (e.g., `&lt;`).
Markdown allows this escape. The slash will not show.

**Comment by alessandroliveri** [comment]
Hi @wooorm thanks for your answer, we noticed the issue because we are saving this string to use it in a HTML element and by doing 
```
const processor = unified()
  .use(remarkParse)
  .use(remarkRehype)
  .use(rehypeReact, {});
  ```
We are seeing these backslashes in the output: do you have any suggestion?

**Comment by wooorm** [comment]
With those projects and that string, that should not happen.
How are you saving/retrieving the string? Cold you make a small repro?

**Comment by alessandroliveri** [comment]
I finally found the issue, we were using the wrong version of `remark-parse` by installing the right one everything seems to be managed as expected.

Thank you for your time
