### ISSUE TITLE
Retain Props on html nodes

### ISSUE THREAD

**Issue by redgumnfp** [rehypejs/rehype-remark#4]
### Subject of the feature
Retain Props on html nodes
OR 
don't convert elements with props

### Problem

I have been building a markdown editor, for use creating an e-learning platform.

I've utilised Remark and Rehype to create and sanitise both markdown and html within the same document, for flexibility purposes. As an example, I am able to add embedded video players, more customisable tables, safer links etc, but only when required - generally we use markdown for simplicity.

This is all working as expected, with one exception: additional props to html elements -> they are converted back to standard markdown elements.

For example, if I added a `open="_blank"` and `rel="noreferrer"` properties to an A tag, this would be stripped when converted to remark using rehype-remark.

Code is as follows:

```
import remark from 'remark'
import remarkParse from 'remark-parse'
import remarkRehype from 'remark-rehype'
import rehypeRaw from 'rehype-raw'
import rehypeSanitize from 'rehype-sanitize'
import rehypeRemark from 'rehype-remark'

const markdownTagNames = ['a', 'p', 'h1']

const markdown = `
# header

<a href="https://github.com/rehypejs/rehype-remark" open="_blank" rel="noreferrer">rehype-remark link (new tab)</a>
`

 remark()
            .use(remarkParse)
            .use(remarkRehype, { allowDangerousHtml: true })
            .use(rehypeRaw)
            .use(rehypeSanitize, { tagNames: markdownTagNames })
            .use(rehypeRemark)
            .processSync(markdown).contents;

```

This outputs:
```
# header

[rehype-remark link (new tab)](https://github.com/rehypejs/rehype-remark)

```
### Expected behavior

Rehype documents containing markdown convertible-nodes should only convert if no properties exist.

### Alternatives

1. A white/black-list config approach to nodes may be a round-about way of ensuring these props exist still
2. Some sort of indicator/property to add so the conversion process only needs to check for the presence of one field

### Workarounds
The main reason I was trying to convert the rehype back to remark was to save the sanitised input, rather than the markdown with tags in the .md file, and sanitize every time they're presented.

In the mean-time, there are two workarounds:

**saving the unsanitised .md files**
This could contain <script> tags for example, but sanitizing them upon presentation.

The main risk of this approach would be forgetting to sanitize the document.

**Injecting open/noreferrer to all a tags on the presentation layer**
A bit carte blanche, but resolves the pen-test issue.

**Creating a separate node for custom conversion**
More a theory, but possibly the most abstract way of doing it. This would result in having non common markup options though.

**Comment by wooorm** [comment]
If you don’t want to loose any information, then why go to markdown at all?

See [this section](https://github.com/syntax-tree/hast-util-to-mdast#html-in-markdown) for when you want certain things as HTML in markdown instead.

> [...] was to save the sanitised input

Why not uhm, save the [sanitized input](https://github.com/rehypejs/rehype-sanitize)?

> Injecting open/noreferrer to all a tags on the presentation layer

if this issue is really only about those, then that’s possible, yeah.

**Comment by wooorm** [comment]
Closing as this seems more like a question than something actionable to change here.
