### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by maccman** [rehypejs/rehype-remark#5]
Can I sponsor some typescript types for this project?

**Comment by wooorm** [comment]
Hi Alex!

We do accept PRs for types, [here are some examples](https://github.com/search?o=desc&q=user%3Arehypejs+types+is%3Apr&s=created&type=Issues). And we do accept [financial support](https://github.com/rehypejs/.github/blob/main/contributing.md#financial-support)!

I’m working on migrating everything to [ESM + JSDoc based types](https://github.com/unifiedjs/unified/issues/121). About 200 out of 450 projects are done, which bubble from low-level up towards more high-level projects like this one. I am now at the “bottleneck” of micromark, which I expect to take a couple of weeks. I expect to reach higher level projects like this one, which are more stable and less involved, in 30-45 days.
